services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskdb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:

